### PR TITLE
[PROPOSAL] Refactor Group Code

### PR DESCRIPTION
**Pull request by ClavinJune**
# Usage Example

```go
package main

import (
  "fmt"
  "log"
  "net/http"
  "time"

  "github.com/ngamux/ngamux"
)

func handler(rw http.ResponseWriter, r *http.Request) error {
  fmt.Fprintln(rw, r.URL.Path)
  return nil
}

func mw(next ngamux.HandlerFunc) ngamux.HandlerFunc {
  return func(rw http.ResponseWriter, r *http.Request) error {
    now := time.Now()
    defer func() {
      log.Println(r.URL.Path, time.Since(now))
    }()

    return next(rw, r)
  }
}

func main() {
  mux := ngamux.NewNgamux()

  mux.GroupPrefix("/api", func(api *ngamux.Ngamux) {
    api.Get("/foo", mw(handler))
    api.Get("/bar", mw(handler))
  })

  http.ListenAndServe(":8080", mux)
}

```

### CODE REVIEW

**Comment by hadihammurabi** [comment]
Great, i see Laravel or AdonisJS way here.

But, you can see in [example](https://github.com/ngamux/ngamux-example/blob/master/group/group.go), we group every route by this way.
```go
mux := ngamux.NewNgamux()
users := mux.Group("/users")
users.Get("/", func(rw http.ResponseWriter, r *http.Request) error {
  fmt.Fprintln(rw, "GET /users")
  return nil
})
users.Post("/", func(rw http.ResponseWriter, r *http.Request) error {
  fmt.Fprintln(rw, "POST /users")
  return nil
})
```
It's done by some library in Go and we need to be familiar for readability.

I think this is just API difference, and no problem with that.
We can discuss.

**Comment by ClavinJune** [comment]
We can also create group like that, my major point in this PR is removing duplicated functions in `group.go`

**Comment by ClavinJune** [comment]
I add another interface option so we can use the current grouping style like below

```go
func main() {
	mux := ngamux.NewNgamux()

	api := mux.Group("/api")
	api.Get("/foo", mw(handler))
	api.Get("/bar", mw(handler))

	http.ListenAndServe(":8080", mux)
}
```

**Comment by hadihammurabi** [comment]
> We can also create group like that, my major point in this PR is removing duplicated functions in `group.go`

Alright. I see.
I have done in [feature/route-group](https://github.com/ngamux/ngamux/tree/feature/route-group) branch.

I hope you can give more suggestion about that.

**Comment by ClavinJune** [comment]
> > We can also create group like that, my major point in this PR is removing duplicated functions in `group.go`
> 
> Alright. I see.
> I have done in [feature/route-group](https://github.com/ngamux/ngamux/tree/feature/route-group) branch.
> 
> I hope you can give more suggestion about that.

I don't understand why we need `parent` there, it only adds complexity and more code. Could u please elaborate?

**Comment by hadihammurabi** [comment]
Yes, `parent` save all information about routes.
When we need to make a child route or sub-route, we can just append the parent path.
For example:
- group path: /users
  - child path: /users + /
  - child path: /users + /:id
  - child path: /users + /:id/posts
and then we can append to routes map.

I know this is not the best code, but it easier to manage middlewares for each group.
For example:
```go
users := mux.Group("/users", mw, mw1, mw2, mw3)
users.Get("/", usersHandler)
```

**Comment by ClavinJune** [comment]
I see, I understand the concern.

But handling middlewares like that will create a performance issue later, since u handle all the middlewares on the ServeHTTP, not in `buildRoute`.

It's okay, I don't have any problem with that, since my goal is only to remove the `group.go` :tada: 

You can close this proposal if needed, cheers.

**Comment by hadihammurabi** [comment]
Alright. Now, i can't sleep for middlewares handling. LOL.

**Comment by ClavinJune** [comment]
> Alright. Now, i can't sleep for middlewares handling. LOL.

that's why I give the user a free will to handle the middleware

**Comment by hadihammurabi** [comment]
Ohhh i see. Because user handled middlewares will run on boot time, not per request.

Yeah. Thanks for suggestions.

**Comment by hadihammurabi** [comment]
resolved at commit [ce178ac8cece83e158fb3b5e8c8eb16e725ad7db](https://github.com/ngamux/ngamux/commit/ce178ac8cece83e158fb3b5e8c8eb16e725ad7db)

**Pull request closed without merging**
